// FFXI Macro Manager — spell, job-ability and job lookup tables
//
// Data is loaded from JSON files generated by tools/generate-data.sh
// out of Windower's own res/*.lua resources. The .exe expects those
// JSON files in a sibling `data/` folder.

using System;
using System.Collections.Generic;
using System.IO;
using System.Web.Script.Serialization;

namespace FFXIMacroManager.Data
{
    public sealed class Spell
    {
        public int    Id;
        public string En     = "";
        public string Prefix = "";     // "/magic", "/song", "/ninjutsu" etc.
        public string Type   = "";     // "WhiteMagic", "BlueMagic", "BardSong" etc.
        public bool   Unlearnable;
        public Dictionary<int,int> Levels = new Dictionary<int,int>(); // job_id -> level

        public int LearnLevelFor(int jobId)
        {
            int lv;
            return Levels.TryGetValue(jobId, out lv) ? lv : 0;
        }

        // The command the user would type in chat to cast this spell.
        public string MacroCommand()
        {
            // Bard songs use /ma in macros (the /song prefix only applies to
            // /song chat shortcut). /magic is universal for spells, /jobability
            // for JAs, etc.  Windower's `prefix` field is what /input prefers.
            string cmd = Prefix;
            if (string.IsNullOrEmpty(cmd)) cmd = "/magic";
            if (cmd == "/magic" || cmd == "/song") cmd = "/ma";
            if (cmd == "/ninjutsu")               cmd = "/ma";
            if (cmd == "/summon")                 cmd = "/ma";
            if (cmd == "/bluemagic")              cmd = "/ma";
            if (cmd == "/geomancy")               cmd = "/ma";
            if (cmd == "/trust")                  cmd = "/ma";
            return cmd + " \"" + En + "\" <stnpc>";
        }

        // Trusts are stored as spells with type "Trust"; we exclude these
        // from the per-job magic lists.  Same for the unlearnable mob-only
        // entries that are kept in resources.spells for completeness.
        public bool IsRealSpell()
        {
            if (Unlearnable) return false;
            if (Type == "Trust") return false;
            return Prefix != "";
        }
    }

    public sealed class JobAbility
    {
        public int    Id;
        public string En     = "";
        public string Prefix = "";
        public string Type   = "";

        public string MacroCommand()
        {
            string cmd = Prefix;
            if (string.IsNullOrEmpty(cmd)) cmd = "/jobability";
            if (cmd == "/jobability")   cmd = "/ja";
            if (cmd == "/pet")          cmd = "/pet";
            if (cmd == "/weaponskill")  cmd = "/ws";
            return cmd + " \"" + En + "\" <t>";
        }
    }

    public sealed class JobInfo
    {
        public int    Id;
        public string Short = "";   // "WHM"
        public string Long  = "";   // "White Mage"
    }

    public sealed class WeaponSkill
    {
        public int    Id;
        public string En    = "";
        public int    Skill = 0;     // 1=hand-to-hand, 2=dagger, 3=sword, ... see Windower res/skills.lua

        public string MacroCommand(string target)
        {
            return "/ws \"" + En + "\" " + (string.IsNullOrEmpty(target) ? "<t>" : target);
        }
    }

    public static class SpellDb
    {
        public static Dictionary<int, Spell>       Spells       { get; private set; } = new Dictionary<int, Spell>();
        public static Dictionary<int, JobAbility>  Abilities    { get; private set; } = new Dictionary<int, JobAbility>();
        public static Dictionary<int, WeaponSkill> WeaponSkills { get; private set; } = new Dictionary<int, WeaponSkill>();
        public static Dictionary<int, JobInfo>     Jobs         { get; private set; } = new Dictionary<int, JobInfo>();

        public static string DataFolder { get; private set; } = "data";
        public static bool Loaded { get; private set; }
        public static string LoadError { get; private set; }

        public static bool TryLoad(string folder)
        {
            try
            {
                DataFolder = folder;
                var jss = new JavaScriptSerializer();
                jss.MaxJsonLength = 8 * 1024 * 1024;

                // ---- spells ----
                var spellsRaw = jss.DeserializeObject(File.ReadAllText(Path.Combine(folder, "spells.json")))
                                as Dictionary<string, object>;
                Spells.Clear();
                foreach (var kv in spellsRaw)
                {
                    var d = (Dictionary<string, object>)kv.Value;
                    var s = new Spell {
                        Id          = ToInt(d, "id"),
                        En          = ToStr(d, "en"),
                        Prefix      = ToStr(d, "prefix"),
                        Type        = ToStr(d, "type"),
                        Unlearnable = ToBool(d, "unlearnable"),
                    };
                    var lvDict = d.ContainsKey("levels") ? d["levels"] as Dictionary<string, object> : null;
                    if (lvDict != null)
                    {
                        foreach (var lv in lvDict)
                            s.Levels[int.Parse(lv.Key)] = Convert.ToInt32(lv.Value);
                    }
                    Spells[s.Id] = s;
                }

                // ---- job abilities ----
                var jasRaw = jss.DeserializeObject(File.ReadAllText(Path.Combine(folder, "job_abilities.json")))
                             as Dictionary<string, object>;
                Abilities.Clear();
                foreach (var kv in jasRaw)
                {
                    var d = (Dictionary<string, object>)kv.Value;
                    var a = new JobAbility {
                        Id     = ToInt(d, "id"),
                        En     = ToStr(d, "en"),
                        Prefix = ToStr(d, "prefix"),
                        Type   = ToStr(d, "type"),
                    };
                    Abilities[a.Id] = a;
                }

                // ---- weapon skills ----
                var wsRaw = jss.DeserializeObject(File.ReadAllText(Path.Combine(folder, "weapon_skills.json")))
                            as Dictionary<string, object>;
                WeaponSkills.Clear();
                foreach (var kv in wsRaw)
                {
                    var d = (Dictionary<string, object>)kv.Value;
                    var w = new WeaponSkill {
                        Id    = ToInt(d, "id"),
                        En    = ToStr(d, "en"),
                        Skill = ToInt(d, "skill"),
                    };
                    WeaponSkills[w.Id] = w;
                }

                // ---- jobs ----
                var jobsRaw = jss.DeserializeObject(File.ReadAllText(Path.Combine(folder, "jobs.json")))
                              as Dictionary<string, object>;
                Jobs.Clear();
                foreach (var kv in jobsRaw)
                {
                    var d = (Dictionary<string, object>)kv.Value;
                    var j = new JobInfo {
                        Id    = int.Parse(kv.Key),
                        Short = ToStr(d, "ens"),
                        Long  = ToStr(d, "en"),
                    };
                    Jobs[j.Id] = j;
                }

                // ---- auto-translate names ----
                AutoTranslateDb.LoadFromFile(Path.Combine(folder, "auto_translates.json"));

                Loaded = true;
                LoadError = null;
                return true;
            }
            catch (Exception ex)
            {
                Loaded = false;
                LoadError = ex.Message;
                return false;
            }
        }

        // Returns spells learnable by jobId, sorted by level then name.
        // Excludes trusts, unlearnable entries, and spells the job never gets.
        public static List<Spell> SpellsForJob(int jobId)
        {
            var list = new List<Spell>();
            foreach (var s in Spells.Values)
            {
                if (!s.IsRealSpell()) continue;
                if (s.LearnLevelFor(jobId) <= 0) continue;
                list.Add(s);
            }
            list.Sort(delegate(Spell a, Spell b) {
                int la = a.LearnLevelFor(jobId), lb = b.LearnLevelFor(jobId);
                if (la != lb) return la.CompareTo(lb);
                return string.Compare(a.En, b.En, StringComparison.OrdinalIgnoreCase);
            });
            return list;
        }

        // Returns weapon skills alpha-sorted.  We don't filter by job here
        // because the skill->job mapping isn't in Windower's raw data; the
        // UI search box does the heavy lifting.
        public static List<WeaponSkill> WeaponSkillsFor(int jobId)
        {
            var list = new List<WeaponSkill>(WeaponSkills.Values);
            list.Sort(delegate(WeaponSkill a, WeaponSkill b) {
                return string.Compare(a.En, b.En, StringComparison.OrdinalIgnoreCase);
            });
            return list;
        }

        // Returns job abilities filtered by jobId.
        //   jobId <= 0 -> all jobs (the "(all jobs)" option) — excludes
        //                 only mob-only entries.
        //   jobId  > 0 -> only abilities that job natively uses.
        //
        // Filtering combines (a) a per-type owner map for categories that
        // are 100% one job (BloodPactRage = SMN, Scholar = SCH, Waltz =
        // DNC, etc.) and (b) a per-name map for the 236 generic JobAbility
        // entries and the 30 PetCommand entries. See Models/JobAbilityMap.cs
        // for the source-of-truth tables.
        public static List<JobAbility> AbilitiesFor(int jobId)
        {
            var list = new List<JobAbility>();
            foreach (var a in Abilities.Values)
            {
                if (jobId <= 0)
                {
                    // "all jobs" — still exclude mob abilities from a
                    // human-facing list (236 + 30 + the type-tagged ones
                    // is plenty, no need to surface 120 mob abilities).
                    if (a.Type == "Monster") continue;
                }
                else
                {
                    if (!Models.JobAbilityMap.Belongs(a.En, a.Type, jobId)) continue;
                }
                list.Add(a);
            }
            list.Sort(delegate(JobAbility a, JobAbility b) {
                return string.Compare(a.En, b.En, StringComparison.OrdinalIgnoreCase);
            });
            return list;
        }

        // ------------------------------------------------------------------
        // helpers
        // ------------------------------------------------------------------
        static int  ToInt (Dictionary<string,object> d, string k) {
            object v;
            if (!d.TryGetValue(k, out v) || v == null) return 0;
            return Convert.ToInt32(v);
        }
        static string ToStr(Dictionary<string,object> d, string k) {
            object v;
            if (!d.TryGetValue(k, out v) || v == null) return "";
            return v.ToString();
        }
        static bool ToBool(Dictionary<string,object> d, string k) {
            object v;
            if (!d.TryGetValue(k, out v) || v == null) return false;
            return Convert.ToBoolean(v);
        }
    }

    // Auto-translate ID -> English text, used to decode the {AT:cat/kind/id}
    // placeholders we produce when reading mcr*.dat lines.
    public static class AutoTranslateDb
    {
        static Dictionary<int, string> _byId = new Dictionary<int, string>();

        public static void LoadFromFile(string path)
        {
            try
            {
                var jss = new JavaScriptSerializer();
                jss.MaxJsonLength = 8 * 1024 * 1024;
                var raw = jss.DeserializeObject(File.ReadAllText(path))
                          as Dictionary<string, object>;
                _byId.Clear();
                if (raw == null) return;
                foreach (var kv in raw)
                {
                    int id; if (!int.TryParse(kv.Key, out id)) continue;
                    _byId[id] = kv.Value == null ? "" : kv.Value.ToString();
                }
            }
            catch { }
        }

        // The category/kind bytes in mcr*.dat tell the game which subtable
        // to use; the ID is unique across the auto-translates.lua file
        // either way, so we use just the ID for lookup.
        public static string Lookup(int category, int kind, int id)
        {
            string s;
            if (_byId.TryGetValue(id, out s) && !string.IsNullOrEmpty(s))
                return s;
            return null;
        }
    }
}
